name: CI Tests
on:
  push:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      functional_tests_group:
        description: Run arbitrary functional tests group by name or all (short and long) tests (default)
        required: true
        default: all
jobs:
  phpcompatibility:
    runs-on: ubuntu-latest
    name: PHP Compatibility
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PHPCompatibility
        uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: 7.4-

  phpcs:
    runs-on: ubuntu-latest
    name: PHP Coding Standards
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: gd, mbstring, zip, ssh2-1.3.1
          coverage: pcov
          ini-values: error_reporting=E_ALL
      - name: Install composer
        run: composer install --no-interaction --prefer-dist
      - name: Run tests
        run: composer cs

  functional:
    runs-on: ${{ matrix.operating-system }}
    name: Functional testing matrix - PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    if: ${{ github.repository_owner == 'pantheon-systems' }}
    strategy:
      matrix:
        operating-system: [ 'macos-latest' ]
        php-versions: [ '7.4', '8.2' ]
      max-parallel: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, mbstring, zip, ssh2-1.3.1
          coverage: pcov
          ini-values: error_reporting=E_ALL
      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Functional Tests (short)
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event.inputs.functional_tests_group == 'all' }}
        run: composer test:short
      - name: Functional Tests (long)
        if: ${{ github.event_name == 'schedule' || github.event.inputs.functional_tests_group == 'all' }}
        run: composer test:long
      - name: Functional Tests (arbitrary group)
        if: ${{ github.event.inputs.functional_tests_group != '' && github.event.inputs.functional_tests_group != 'all' }}
        run: composer test:group -- ${{ github.event.inputs.functional_tests_group }}
      - name: Coverage Report
        run: composer coverage
      - name: Save coverage as artifact
        uses: actions/upload-artifact@v2
        with:
          name: CoverageReport
          path: docs/TestCoverage.md
